name: Opensource Vulnerability Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: Scan repository for Issues

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2.1.15
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create-issues: false 
#           quick: true
#           fail-on-cvss: 1
#           min-cvss-for-issue: 1

  Veracode-container_iac_secrets-scan:
    runs-on: ubuntu-latest
    name: Veracode Container/IaC/Secrets scan

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Veracode Container/IaC/Secrets action step
        uses: veracode/container_iac_secrets_scanning@v1.0.7
        with:
          vid: ${{ secrets.VID }}
          vkey: ${{ secrets.VKEY }}
          command: "scan" 
          type: "directory"
          source: "./"
          format: "json"
          debug: false
          fail_build: true
          
  # Veracode-container_iac_secrets-scan:
  #   runs-on: ubuntu-latest
  #   name: Verracode Container/IaC/Secrets scan

  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v3

  #     - name: Verracode Container/IaC/Secrets action step
  #       uses: veracode/container_iac_secrets_scanning@v1.0.1
  #       with:
  #         vid: ${{ secrets.VID }}
  #         vkey: ${{ secrets.VKEY }}
  #         command: "scan" 
  #         type: "directory"
  #         source: "./"
  #         format: "json"
  #         debug: false
  #         fail_build: true

  # Veracode-container_iac_secrets-sbom:
  #   runs-on: ubuntu-latest
  #   name: Veracode Container/IaC/Secrets scan

  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v3

  #     - name: Veracode Container/IaC/Secrets action sbom
  #       uses: veracode/container_iac_secrets_scanning@v1.0.1
  #       with:
  #         vid: ${{ secrets.VID }}
  #         vkey: ${{ secrets.VKEY }}
  #         command: "sbom" 
  #         type: "directory"
  #         source: "./"
  #         format: "cyclonedx-json"
  #         debug: false
  #         fail_build: false
